# Robot status
int32 state  # Possible states: 
              # 0 = init, 
              # 1 = home, 
              # 2 = waiting_for_dice, 
              # 3 = scanning_dice
              # 4 = moving_to_dice, 
              # 5 = picking up dice, 
              # 6 = verify with robocop,
              # 7 = move to handoff, 
              # 8 = ready/initiate handoff
              # 9 = error, 

